sudo: required
language: generic
services:
  - docker
  
before_install:
  - docker build -t julianshaw2000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true julianshaw2000/docker-react npm run test